cabal-version:      2.4
name:               prolog-library
version:            0.1.0.0
synopsis:           A minimal Prolog interpreter in Haskell
license:            MIT
build-type:         Simple

executable prolog-library
  main-is:          Prolog_Library.hs
  other-modules:    Term
                  , Unify
                  , Interpret
                  , Parse
                  , Examples
                  , ListOps
                  , Graph
                  , Tests
  hs-source-dirs:   src
  build-depends:    base >=4.14 && <5
                  , mtl
                  , parsec
  default-language: Haskell2010
  ghc-options:      -Wall -Wno-incomplete-patterns -Wno-overlapping-patterns
